### PR TITLE
[MRG] Make methods/attributes private

### LINKED ISSUE #448: Make some methods of `Module` private
Currently, many methods that should not be user facing are user facing:
- `init_morph()`
- `get_states_from_nodes_and_edges()`
- `initialized`
- `initialize()`

Possibly also:
- `to_jax()`
- `get_all_parameters()`

but those might be needed once we expose the update loop.

Also, `Compartment.init_conds()`, `Cell.update_summed_coupling_conductances()` (why do we still have this at all?), `Network.init_syns()`.

### PR DESCRIPTION
**Pull request by ntolley**
Closes #448

@michaeldeistler @jnsbck is the list of methods/attributes to make private actually agreed upon? Here's what was stated int he issue:

```
"par_inds",
"child_inds",
"child_belongs_to_branchpoint",
"solve_indexer",
"cells_list",
"cumsum_nbranchpoints_per_cell",
"cumsum_nbranches"
```
I've started with `par_inds` to get a feel for the code base, but I'll wait for you input before continuing

### CODE REVIEW

**Comment by michaeldeistler** [comment]
Hi Nick! Great that you are getting into Jaxley!

And yes, the list is agreed upon! Thanks for tackling it, let us know if anything is unclear!

Michael

**Comment by ntolley** [comment]
Definitely happy to help out! Super cool project that I think will be great for my research questions

 I think I've covered all the attributes so this is ready for review

**Comment by michaeldeistler** [comment]
Awesome! Automated tests are failing right now because of `black`. Could you run:
```
black jaxley
black tests
```

Thanks a ton!

**Comment by jnsbck** [comment]
Hey! Welcome on board also from my side! :) Cool to have you also working on `Jaxley`. Feel free to reach out at any time if you have questions or ideas :)

**Review by michaeldeistler — APPROVED** [review]
Tests are passing, and all looks good now! Thanks @ntolley!

**Pull request merged**
