### PR TITLE
Checked if the recodings are empty

### LINKED ISSUE #365: an explicit error when no recordings are inserted
When no recordings are inserted the `jx.integrate` currently gives a cryptic error:
```python
comp = jx.Compartment()
v = jx.integrate(comp, t_max=10.0)
```

We should raise a more explicit error by checking whether `module.recordings.rec_index` is empty.

### PR DESCRIPTION
**Pull request by deezer257**
I inserted a check if the recording DataFrame is empty, if so I raised an value error. Nevertheless, I use a WSL and at some point the tests got stuck, at about 80% of completion, and  the WSL lost connection.

Closes #365

### CODE REVIEW

**Review by michaeldeistler — CHANGES_REQUESTED** [review]
Thanks! Please add a quick test to `tests/` that checks whether this indeed raises an error. E.g.
```python
comp = jx.Compartment()
with pytest.raises(ValueError):
    v = jx.integrate(comp, delta_t=0.025, t_max=10.0)
```

**Comment by deezer257** [comment]
Test is implemented.

**Comment by michaeldeistler** [comment]
Thanks! But the test is not a Python file. Please add the test to `tests/test_record_and_stimulate.py` and create a `def test_empty_recordings()` there.

**Comment by michaeldeistler** [comment]
Tests are not passing. You probably did not run `black tests`?

**Comment by deezer257** [comment]
I only ran the specific test since all tests would take an hour to run. I will do it tomorrow, sorry!

**Comment by michaeldeistler** [comment]
Thanks again! `black` passes now, but the test you wrote now exists twice :D 

(You can always check [changed files](https://github.com/jaxleyverse/jaxley/pull/460/files) to see what you are trying to merge). Could you delete the `tests/test_empty_recording` file?

**Review by michaeldeistler — APPROVED** [review]
Looks great now, thanks a ton! I will merge once tests have passed.

**Pull request merged**
