### PR TITLE
Ensure Changelog is updated with every PR.

### PR DESCRIPTION
**Pull request by jnsbck**
I also like the suggestion of @ntolley to make updating the changelog part of PRs. To avoid having to remind contributors on every PR this could be enforced via github actions. I wrote a little check to do this.

(Quick test: changelog not updated -> tests should fail)

### CODE REVIEW

**Comment by ntolley** [comment]
Definitely a great idea to automate the check! Are you thinking to leave it to the discretion of the maintainer if it's appropriate to ignore the check? (e.g. a typo fix)

**Comment by jnsbck** [comment]
Currently this would be the case, but I am also not so happy about the current implementation at the moment. I also thought about adding a separate workflow i.e. "chores" and incl. isort, black, license header and changelog in there. This would be much cleaner and easier to quickly check for the maintainer as well.

**Comment by jnsbck** [comment]
I did some refactoring:
- Tests/Chores checks for isort, license headers, changelog, black
- Tests/Pytest runs tests
- Tests/Regression Tests runs regression tests only if tests were succesful.

**Comment by jnsbck** [comment]
@michaeldeistler thoughts?

**Review by michaeldeistler — APPROVED** [review]
Sorry, I had missed this one. I like the idea!

**Pull request merged**
